--- makefile
+++ makefile
@@ -1,8 +1,13 @@
 #this is a makefile example
 
-main:main.o
+main:main.o testa testb
 	gcc -o main main.o
 
 main.o:main.c
 	gcc -c main.c
 
+testa:
+	touch testa
+
+testb:
+	touch testb
